# Site wide configuration

title:            DATA ZOO
locale:           en_US
url:              http://www.datazoo.de


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Martin Gross
  avatar: MG_Profilbild.jpg
  bio: "Software Engineer, founder and father."
  email: 
  disqus-shortname: datazoo
  twitter: MartinGross
  facebook: #username
  google:
    plus: MartinGrossMG
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: MartinGross
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: martingrossfluxum
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
